### ISSUE TITLE
Sample input needed for the sql-query-generator chain

### ISSUE THREAD

**Issue by SaiMeher69** [danieljpalmer/llm-analyst#3]
While trying to use this in the https://app.relevanceai.com/notebook........... page, giving it sample inputs is always providing the same error which I cant seem to figure out what's happening. I've already tried many many variations of the input for tableColumns field but it always returned the error saying "Studio Params Validation Error: must be object {"type":"object"} /tableColumns/0". 
I'll provide a small sample input here which i tried so you can guide me on how stupid I was.

[
    {
      "id":"INT"
    },
    {
      "user_id":"VARCHAR"
    },
    {
      "gender":"VARCHAR"
    },
    {
      "location":"VARCHAR"
    },
    {
      "age":"INT"
    },
    {
      "purchase_value":"FLOAT"
    },
    {
      "purchase_date":"DATETIME"
    },
    {
      "product_name":"VARCHAR"
    },
    {
      "product_material":"VARCHAR"
    },
    {
      "product_tag":"VARCHAR"
    }
]

another one: 

[
    {
        "items": {
            "properties": {
                "column": "id",
                "type": "INT"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "user_id",
                "type": "VARCHAR"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "gender",
                "type": "VARCHAR"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "location",
                "type": "VARCHAR"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "age",
                "type": "INT"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "purchase_value",
                "type": "FLOAT"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "purchase_date",
                "type": "DATETIME"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "product_name",
                "type": "VARCHAR"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "product_material",
                "type": "VARCHAR"
            }
        }
    },
    {
        "items": {
            "properties": {
                "column": "product_material",
                "type": "VARCHAR"
            }
        }
    }
]

Thanks in advance. pls help T_T

**Comment by SaiMeher69** [comment]
BRO PLEASE REPLY

**Comment by Siddhijain16** [comment]
@SaiMeher69 Any update on this? Will your code works?

**Comment by SaiMeher69** [comment]
@Siddhijain16 Bro we have abandoned this and moved on ages ago so I dont even remember at this point

**Comment by SaiMeher69** [comment]
Closing because not needed

**Comment by Siddhijain16** [comment]
> @Siddhijain16 Bro we have abandoned this and moved on ages ago so I dont even remember at this point

@SaiMeher69 Can you suggest any alternative approach for that ?
